version: 2
updates:
  # Permitir atualizações de versão para npm
  - package-ecosystem: 'npm'
    # Procurar arquivos "package.json" e "lock" no diretório "root"
    directory: '/'
    # Verificar o registro npm para atualizações diárias (dias de semana)
    schedule:
      interval: 'monthly'

  # Habilitar atualizações da versão para Docker
  - package-ecosystem: 'docker'
    # Buscar um "Dockerfile" no diretório "root"
    directory: '/'
    # Verificar atualizações uma vez na semana
    schedule:
      interval: 'monthly'
