name: Publish image to Docker Hub

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: 'projects-service'

jobs:
  # integration-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run Integration tests
  #       run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Checking lint
        run: npm run lint

  version-bump:
    runs-on: ubuntu-latest
    outputs:
      tag_output: ${{ steps.tag_version.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3

      - name: Bump version and push tag
        id: tag_version
        run: bash |
          ./.github/script/version-bump.sh

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: version-bump

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.version-bump.outputs.tag_output }}
