name: 'Projects-service CI'

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Checking lint
        run: npm run lint

      # Turning off for now tests check
      # - name: Running tests
      #   run: npm run test
